name: Serrato-stack 

services:
  api:
    container_name: breast-cancer-api
    image: breast-cancer-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DEBUG=True
    restart: always
